services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: kthais
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  postgres_data:
